# Generated by Django 4.1.5 on 2023-02-01 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='DealerProfile')),
                ('phone', models.CharField(blank=True, max_length=9, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=50)),
                ('car_brand', models.CharField(max_length=55)),
                ('car_km', models.IntegerField(default=0)),
                ('car_condition', models.TextField()),
                ('negotiable', models.BooleanField(default=True)),
                ('car_color', models.CharField(max_length=55)),
                ('car_type', models.CharField(max_length=55)),
                ('car_price', models.FloatField(default=0.0)),
                ('car_model', models.CharField(max_length=55)),
                ('plate', models.CharField(max_length=55)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Dealer.dealerprofile')),
            ],
        ),
    ]
